import { createDefaultTranslator } from "@/i18n/default-translator";
import defaultMessages from "@/i18n/generated/default-en/LibProposalsCopy.json";

const i18n = createDefaultTranslator("LibProposalsCopy", defaultMessages);

export const proposalCopy = {
  signInRequired: () => i18n("signInRequired"),
  notFound: () => i18n("notFound"),
  notParticipant: () => i18n("notParticipant"),
  expectedBodyHash: () => i18n("expectedBodyHash"),
  expectedHex: () => i18n("expectedHex"),
  transactionTooLarge: (maxBytes: number) => i18n("transactionTooLarge", { maxBytes }),
  witnessSetTooLarge: (maxBytes: number) => i18n("witnessSetTooLarge", { maxBytes }),
  buildContextTooDeep: (maxDepth: number) => i18n("buildContextTooDeep", { maxDepth }),
  buildContextTooLarge: (maxBytes: number) => i18n("buildContextTooLarge", { maxBytes }),
  malformedNonce: () => i18n("malformedNonce"),
  nonceAddressMismatch: () => i18n("nonceAddressMismatch"),
  nonceExpired: () => i18n("nonceExpired"),
  activeProposalLimit: (limit: number) => i18n("activeProposalLimit", { limit }),
  dailyProposalLimit: (limit: number) => i18n("dailyProposalLimit", { limit }),
  changedWhileRebuilding: () => i18n("changedWhileRebuilding"),
  alreadyChanging: () => i18n("alreadyChanging"),
  changedWhileSubmitting: () => i18n("changedWhileSubmitting"),
  changedWhileCancelling: () => i18n("changedWhileCancelling"),
  status: (status: string) => i18n("status", { status: status.toLowerCase() }),
  rebuiltBeforeSigning: () => i18n("rebuiltBeforeSigning"),
  onlyProposerCanRebuild: () => i18n("onlyProposerCanRebuild"),
  changedBeforeRebuilding: () => i18n("changedBeforeRebuilding"),
  changedBeforeSubmitting: () => i18n("changedBeforeSubmitting"),
  onlyProposerCanCancel: () => i18n("onlyProposerCanCancel"),
  requestFailed: (status: number) => i18n("requestFailed", { status }),
  couldNotDecodeTransaction: () => i18n("couldNotDecodeTransaction"),
  couldNotDecodeTransactionBytes: () => i18n("couldNotDecodeTransactionBytes"),
  checkedInputLimit: (limit: number, count: number) =>
    i18n("checkedInputLimit", { limit, count }),
  couldNotConfirmInput: (input: string) => i18n("couldNotConfirmInput", { input }),
  inputSpent: (input: string) => i18n("inputSpent", { input }),
  transactionExpired: () => i18n("transactionExpired"),
  storedBodyHashMismatch: () => i18n("storedBodyHashMismatch"),
  stateInputNotConsumed: () => i18n("stateInputNotConsumed"),
  walletIdentityMismatch: () => i18n("walletIdentityMismatch"),
  noInputsVerified: () => i18n("noInputsVerified"),
  invalidStoredWitness: (signer: string) => i18n("invalidStoredWitness", { signer }),
  stateTokenMissing: () => i18n("stateTokenMissing"),
  signersUnresolved: () => i18n("signersUnresolved"),
  claimedBodyHashMismatch: () => i18n("claimedBodyHashMismatch"),
  liveStateMissing: () => i18n("liveStateMissing"),
  rebuildUnavailable: (_builder: string) => i18n("rebuildUnavailable"),
  buildContextMissing: () => i18n("buildContextMissing"),
  invalidWitnessSet: () => i18n("invalidWitnessSet"),
  invalidWitnessIdentifiers: () => i18n("invalidWitnessIdentifiers"),
  couldNotDecodeWitnessSet: () => i18n("couldNotDecodeWitnessSet"),
  vkeyWitnessesOnly: () => i18n("vkeyWitnessesOnly"),
  witnessCountRange: () => i18n("witnessCountRange"),
  invalidWitnessSignature: () => i18n("invalidWitnessSignature"),
  witnessSignerMismatch: () => i18n("witnessSignerMismatch")
};
