import { act, renderHook } from "@testing-library/react";
import { Provider, createStore } from "jotai";
import { expect, it, vi } from "vitest";
import type { PropsWithChildren } from "react";
import { activePaymentKeyHashAtom } from "@/providers/wallet.atoms";
import { sttStateFormAtom, sttWalletInputsAtom } from "./atoms/forms/stt-spend-form.atoms";
import { lockedContractUtxosAtom, lockedContractUtxosLoadingAtom } from "./atoms/workspace-data.atoms";
import { WorkspaceActionsProvider } from "./workspace-actions-context";
import type { PermissionWalletWorkspaceState } from "./use-permission-wallet-workspace-state";
import { useBeneficiaryDistribution } from "./use-beneficiary-distribution";
const mocks = vi.hoisted(() => ({ derive: vi.fn(() => ({ details: null, error: null })) }));
vi.mock("./beneficiary-distribution-model", () => ({ deriveBeneficiaryDistributionPreview: mocks.derive }));
it("updates the distribution model when input, chain data, State or actor changes", () => {
  const store = createStore();
  const navigate = vi.fn();
  const wrapper = ({ children }: PropsWithChildren) => <Provider store={store}><WorkspaceActionsProvider value={{ openWorkspaceIntent: navigate, refreshLockedContractUtxos: vi.fn() } as unknown as PermissionWalletWorkspaceState}>{children}</WorkspaceActionsProvider></Provider>;
  const { result } = renderHook(useBeneficiaryDistribution, { wrapper });
  const input = { txHash: "aa".repeat(32), outputIndex: 0 };
  act(() => result.current.setSelectedRefs([input]));
  expect(store.get(sttWalletInputsAtom)).toEqual([input]);
  expect(mocks.derive).toHaveBeenLastCalledWith(expect.objectContaining({ selectedRefs: [input] }));
  const utxos = [{ input, output: { address: "wallet", amount: [{ unit: "lovelace", quantity: "6000000" }] } }];
  act(() => { store.set(lockedContractUtxosAtom, utxos); store.set(lockedContractUtxosLoadingAtom, true); store.set(activePaymentKeyHashAtom, "11".repeat(28)); });
  expect(mocks.derive).toHaveBeenLastCalledWith(expect.objectContaining({ utxos, loading: true, signer: "11".repeat(28) }));
  const nextState = { ...store.get(sttStateFormAtom), walletName: "Changed wallet" };
  act(() => store.set(sttStateFormAtom, nextState));
  expect(mocks.derive).toHaveBeenLastCalledWith(expect.objectContaining({ form: nextState }));
  act(() => { result.current.stopStreams(); result.current.settle(); });
  expect(navigate).toHaveBeenCalledWith("send", "stop-beneficiary-stream");
  expect(navigate).toHaveBeenCalledWith("pay-streaming-payments", "payout-streaming-payment", "streaming-payments-pay-due");
});
